#ifndef __STEPPER_MOTOR_H__
#define __STEPPER_MOTOR_H__

#define BOX_MOTOR_ENABLE 25

#define BOX_LEFT_MOTOR_CLK 29
#define BOX_RIGHT_MOTOR_CLK 24
#define BOX_LEFT_MOTOR_DIR 28
#define BOX_RIGHT_MOTOR_DIR 27

#define SUPPORT_MOTOR_ENABLE 23

#define SUPPORT_LEFT_MOTOR_CLK 22
#define SUPPORT_RIGHT_MOTOR_CLK 21
#define SUPPORT_LEFT_MOTOR_DIR 26
#define SUPPORT_RIGHT_MOTOR_DIR 30

void setWiringPi();

#endif
